nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/':
            allow_origin: ['http://localhost:5173']
            allow_headers: ['Content-Type', 'X-CSRF-TOKEN']
            allow_methods: ['POST', 'GET', 'OPTIONS']
